### ISSUE TITLE
Add style

### ISSUE THREAD

**Issue by HugoOjvindFrancois** [Pop115/Popix#11] opened 2022-12-12 11:18 UTC
As a Popix user,
I would like the website to be stylish
So I can feel comfortable while winning.

Maybe check this for a good starting point : [What is CSS](https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/What_is_CSS)

**Comment by Pop115** [comment] 2022-12-12 11:20
Duplicate of https://github.com/Pop115/Popix/issues/6

**Closed by Pop115** 2022-12-12 11:20 UTC

**Comment by Pop115** [comment] 2022-12-12 11:22
aaaaaaa
